# This file contains default values, and does not need to be edited. All
# important settings can be changed from the admin interface.

defaults: &defaults
  site_title: Mastodon
  site_short_description: ''
  site_description: ''
  site_extended_description: ''
  site_terms: ''
  site_contact_username: ''
  site_contact_email: ''
  registrations_mode: 'none'
  registrations_limit: 0
  registrations_limit_per_day: 0
  registrations_start_hour: 0
  registrations_end_hour: 24
  registrations_secondary_start_hour: 0
  registrations_secondary_end_hour: 0
  profile_directory: true
  closed_registrations_message: ''
  timeline_preview: true
  show_staff_badge: true
  preview_sensitive_media: false
  noindex: false
  theme: 'system'
  trends: true
  trends_as_landing_page: true
  trendable_by_default: false
  reserved_usernames:
    - admin
    - support
    - help
    - root
    - webmaster
    - administrator
    - mod
    - moderator
  disallowed_hashtags: # space separated string or list of hashtags without the hash
  bootstrap_timeline_accounts: ''
  activity_api_enabled: true
  peers_api_enabled: true
  show_domain_blocks: 'disabled'
  show_domain_blocks_rationale: 'disabled'
  require_invite_text: false
  backups_retention_period: 7
  delete_content_cache_without_reaction: false
  captcha_enabled: false
  receive_other_servers_emoji_reaction: false
  streaming_other_servers_emoji_reaction: false
  streaming_local_emoji_reaction: true
  enable_emoji_reaction: true
  check_lts_version_only: true
  enable_public_visibility: true
  enable_public_unlisted_visibility: true
  unlocked_friend: false
  stranger_mention_from_local_ng: false
  enable_local_timeline: true
  emoji_reaction_disallow_domains: []

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
