default: styles/application.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
head-space: styles/head-space.scss
head-space-en: styles/head-space-en.scss
head-space-jp: styles/head-space-jp.scss
